#!/usr/bin/env python3
"""Reproduce monochrome mark assets and adapted CC BY-SA 4.0 Portfolio glyphs.

The font data derives from VileR's Oldschool PC Font Pack v2.2:
https://int10h.org/oldschool-pc-fonts/
The generated font is a marked scaling/conversion adaptation. See
LICENSES/CC-BY-SA-4.0.txt and docs/third-party-notices.md. The emblem image
data is separate from the font adaptation.
"""
from pathlib import Path
import re
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
source = ROOT / "main/http_server/axe-os/src/assets/5tratum-emblem.png"
font_source = (ROOT / "main/lv_font_portfolio-6x8.c").read_text()
bitmap_text = font_source.split("glyph_bitmap[] = {", 1)[1].split("};", 1)[0]
bitmap = bytes(int(v, 16) for v in re.findall(r"0x([0-9a-f]+)", re.sub(r"/\*.*?\*/", "", bitmap_text, flags=re.S)))
dsc_text = font_source.split("glyph_dsc[] = {", 1)[1].split("};", 1)[0]
glyphs = [tuple(map(int, m)) for m in re.findall(
    r"bitmap_index = (\d+), .adv_w = (\d+), .box_w = (\d+), .box_h = (\d+), .ofs_x = (-?\d+), .ofs_y = (-?\d+)", dsc_text)]

lines = ['/*',
         ' * Generated by test/host/generate_oled_assets.py; established 5tratum mark.',
         ' * Font data: Portfolio 6x8 from Oldschool PC Font Pack v2.2 by VileR.',
         ' * Original material: https://int10h.org/oldschool-pc-fonts/',
         ' * Adaptation: selected LVGL glyph bitmaps scaled to twice their dimensions.',
         ' * Font arrays/descriptors retain CC-BY-SA-4.0; emblem image data is separate.',
         ' * See LICENSES/CC-BY-SA-4.0.txt and docs/third-party-notices.md.',
         ' */',
         '#ifndef FIVE_TRATUM_OLED_ASSETS_H', '#define FIVE_TRATUM_OLED_ASSETS_H', '#include "lvgl.h"']
for size in (8, 32):
    # Keep the full mark and its proportions. Threshold only for the I1 panel.
    image = Image.open(source).convert("RGBA").resize((size, size), Image.Resampling.LANCZOS)
    pixels = [int(a >= 70 and max(r, g, b) >= 65) for r, g, b, a in image.getdata()]
    packed = [sum(pixels[i+j] << (7-j) for j in range(8)) for i in range(0, len(pixels), 8)]
    data = [0, 0, 0, 255, 255, 255, 255, 255] + packed
    lines += [f'static const uint8_t oled_logo_{size}_data[] = {{',
              '    ' + ', '.join(f'0x{v:02x}' for v in data), '};',
              f'static const lv_image_dsc_t oled_logo_{size} = {{',
              f'    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_I1, .w = {size}, .h = {size}, .stride = {size//8}}},',
              f'    .data_size = sizeof(oled_logo_{size}_data), .data = oled_logo_{size}_data,', '};']

# Native doubled portfolio digits, decimal point and dash. No new font dependency.
chars = "-.0123456789"
out_bitmap, descriptors = [], [(0, 0, 0, 0, 0, 0)]
for char in chars:
    index, adv, w, h, ox, oy = glyphs[ord(char) + 1]
    bits = [(bitmap[index + i//8] >> (7-i%8)) & 1 for i in range(w*h)]
    doubled = [bits[(y//2)*w+x//2] for y in range(h*2) for x in range(w*2)]
    start = len(out_bitmap)
    for i in range(0, len(doubled), 8):
        out_bitmap.append(sum(v << (7-j) for j,v in enumerate(doubled[i:i+8])))
    descriptors.append((start, adv*2, w*2, h*2, ox*2, oy*2))
lines += ['static const uint8_t oled_large_bitmap[] = {' + ','.join(f'0x{v:02x}' for v in out_bitmap) + '};',
          'static const lv_font_fmt_txt_glyph_dsc_t oled_large_glyphs[] = {']
for i, adv, w, h, ox, oy in descriptors:
    lines.append(f'    {{.bitmap_index={i},.adv_w={adv},.box_w={w},.box_h={h},.ofs_x={ox},.ofs_y={oy}}},')
lines += ['};', 'static const uint16_t oled_large_chars[] = {' + ','.join(str(ord(c)-ord(chars[0])) for c in chars) + '};',
          'static const lv_font_fmt_txt_cmap_t oled_large_cmap[] = {',
          '    {.range_start=45,.range_length=13,.glyph_id_start=1,.unicode_list=oled_large_chars,.list_length=12,.type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY},',
          '};', 'static const lv_font_fmt_txt_dsc_t oled_large_dsc = {',
          '    .glyph_bitmap=oled_large_bitmap,.glyph_dsc=oled_large_glyphs,.cmaps=oled_large_cmap,.cmap_num=1,.bpp=1,', '};',
          'static const lv_font_t oled_large_font = {',
          '    .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,.get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,',
          '    .line_height=16,.base_line=2,.dsc=&oled_large_dsc,.static_bitmap=1,', '};', '#endif']
(ROOT / "main/oled_display_assets.h").write_text("\n".join(lines) + "\n")
print(f"Generated mark and digit font: {len(out_bitmap)} font bytes, 144 image bytes + palettes")
