import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../main/http_server/axe-os/package.json',import.meta.url));
const ts=require('typescript');
const file=new URL('../main/http_server/axe-os/src/app/pages/edit/settings-scope.ts',import.meta.url);
const compiled=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const context={exports:{}};vm.runInNewContext(compiled,context);
const {settingsPatch,changedFields}=context.exports;
const patch=(values,baseline,section,n=2)=>JSON.parse(JSON.stringify(settingsPatch(values,baseline,section,n)));
let checks=0;const equal=(actual,expected)=>{assert.deepEqual(actual,expected);checks++;};
const baseline={frequency:500,coreVoltage:1130,hostname:'qa',ssid:'wifi',wifiPass:'*****',stratumPassword:'*****',fallbackStratumPassword:'*****',stratumPort:7331,fallbackStratumPort:7331,poolMode:1,poolBalance:50,stratumKeep:true,stratumDifficulty:1024,flipScreen:false,timeFormat:'24h',manualFanSpeed:70,fan1ManualSpeed:80,pidP:6,fan1PidP:7,canMaster:false,customMempoolEnabled:true,mempoolUrl:'https://example.test'};
const all={...baseline,frequency:550,coreVoltage:1150,hostname:'edited',stratumPort:65535,fan1ManualSpeed:90,flipScreen:true};
equal(patch(all,baseline,'network'),{hostname:'edited'});
equal(patch(all,baseline,'performance'),{frequency:550,coreVoltage:1150});
equal(patch(all,baseline,'pool'),{pools:[{port:65535},{}]});
equal(patch(all,baseline,'cooling'),{fans:[{},{manualSpeed:90}]});
equal(patch(all,baseline,'cooling',1),{});
equal(patch(all,baseline,'display'),{flipScreen:true});
equal(patch(all,baseline,'scheduler'),{});
equal(patch(all,baseline,'update'),{});
equal(patch(all,baseline,'unknown'),{});
equal(patch({...baseline,fallbackStratumPassword:'replacement'},baseline,'pool'),{pools:[{},{password:'replacement'}]});
equal(patch({...baseline,stratumPassword:'*****'},baseline,'pool'),{});
equal(patch({...baseline,wifiPass:''},baseline,'network'),{wifiPass:''});
equal(patch({...baseline,fan1PidP:8},baseline,'cooling'),{fans:[{},{pid:{p:8}}]});
equal(patch({...baseline,pidP:8},baseline,'cooling'),{fans:[{pid:{p:8}},{}]});
equal(patch({...baseline,customMempoolEnabled:false},baseline,'advanced'),{mempoolCustom:false,mempoolUrl:''});
equal(patch({...baseline,canMaster:true},baseline,'advanced'),{canMaster:true});
equal(patch({...baseline,timeFormat:'12h'},baseline,'display'),{});
equal(patch({...baseline,fallbackSv2AuthorityPubkey:'public-key'},baseline,'pool'),{pools:[{},{sv2AuthorityPubkey:'public-key'}]});
equal(patch(baseline,baseline,'pool'),{});
equal(Array.from(changedFields(all,baseline,'network')),['hostname']);
console.log(JSON.stringify({checks,passed:checks}));
