import { of, Subject } from 'rxjs';
import { OperatingProfilesComponent } from './operating-profiles.component';
import { OperatingProfilesService, Profiles } from 'src/app/services/operating-profiles.service';
import { LiveDataService } from 'src/app/services/live-data.service';
const data: Profiles = { schemaVersion: 1, tuning: Array.from({ length: 10 }, (_, slot) => ({ slot, configured: false, name: null })), pools: Array.from({ length: 10 }, (_, slot) => ({ slot, configured: slot === 2, name: slot === 2 ? 'MUX' : null, host: 'mux.example.test', port: 3333 })), limits: { frequency: { min: 400, max: 625, step: .25, quantization: 'nearest-pll' }, coreVoltage: { min: 1000, max: 1250, step: 1 } }, current: { frequencyMHz: 625.125, coreVoltageMv: 1173 } };
describe('Miner operating profiles', () => {
 let component: OperatingProfilesComponent; let service: jasmine.SpyObj<OperatingProfilesService>;
 beforeEach(() => { service = jasmine.createSpyObj<OperatingProfilesService>('profiles', ['get', 'save', 'apply']); service.get.and.returnValue(of(structuredClone(data))); service.save.and.returnValue(of({ ok: true, restartRequired: false })); service.apply.and.returnValue(of({ ok: true, restartRequired: false })); component = new OperatingProfilesComponent(service, { info$: new Subject() } as unknown as LiveDataService); });
 afterEach(() => component.ngOnDestroy());
 it('retains the existing fractional point without writing when opening manual mode', () => { component.ngOnInit(); component.manual = true; expect(component.frequencyMHz).toBe(625.125); expect(component.coreVoltageMv).toBe(1173); expect(component.pointValid).toBeTrue(); expect(component.pointChanged).toBeFalse(); expect(service.save).not.toHaveBeenCalled(); expect(service.apply).not.toHaveBeenCalled(); });
 it('reviews without writing and applies the reviewed point only on Apply', () => { component.ngOnInit(); component.frequencyMHz = 525.25; component.coreVoltageMv = 1151; component.reviewManual(); expect(service.apply).not.toHaveBeenCalled(); component.apply(); expect(service.apply).toHaveBeenCalledOnceWith({ type: 'tuning', frequencyMHz: 525.25, coreVoltageMv: 1151 }, ''); });
 it('blocks changed points outside bounds or off the request increment', () => { component.ngOnInit(); for (const frequency of [626, 525.1, NaN]) { component.frequencyMHz = frequency; component.reviewManual(); expect(component.review).toBeUndefined(); } expect(service.apply).not.toHaveBeenCalled(); });
 it('saves a named point on the miner without applying it', () => { component.ngOnInit(); component.names[4] = 'My point'; component.save(4); expect(service.save).toHaveBeenCalledOnceWith({ type: 'tuning', slot: 4, name: 'My point', frequencyMHz: 625.125, coreVoltageMv: 1173 }, ''); expect(service.apply).not.toHaveBeenCalled(); });
 it('uses the reviewed pool target and keeps passwords out of browser Apply', () => { component.type = 'pool'; component.ngOnInit(); component.poolTarget = 'fallback'; component.reviewSlot(component.slots[2]); component.poolTarget = 'primary'; component.apply(); expect(service.apply).toHaveBeenCalledOnceWith({ type: 'pool', slot: 2, poolTarget: 'fallback' }, ''); });
 it('keeps controls busy until the committed snapshot is refreshed', () => { component.ngOnInit(); const next = new Subject<Profiles>(); service.get.and.returnValue(next); component.names[0] = 'Point'; component.save(0); expect(component.busy).toBeTrue(); component.clear(0); expect(service.save).toHaveBeenCalledTimes(1); next.next(structuredClone(data)); next.complete(); expect(component.busy).toBeFalse(); });
});
